### ISSUE TITLE
environment_variables.device_service_environment_variable.get_all_by_application(id) output is different from the docs

### ISSUE THREAD

**Issue by nghiant2710** [balena-io/balena-sdk-python#204]
There is no device information for the environment variables.

**Comment by otaviojacobi** [comment]
Hello, indeed some examples of the SDK were outdated. Since #326 instead of exammples withing the SDK docs itself, we are using type hints to inform the returned types and they should be mantained more strictly. Please check https://docs.balena.io/reference/sdk/python-sdk/#types for all the returned types.
