### ISSUE TITLE
Python SDK: login with MFA

### ISSUE THREAD

**Issue by mfoglio** [balena-io/balena-sdk-python#285]
I have two factors authentication enabled. I generate an OPT code using an app on my phone. How can I login using the Python SDK?
So far I am using this code:
```
balena = Balena()
credentials = {
    "username": settings.BALENA_USERNAME,
    "password": settings.BALENA_PASSWORD
}
balena.auth.login(**credentials)
balena.twofactor_auth.challenge("303206")  # OTP code
print(balena.twofactor_auth.is_passed())
```
But I get the error: `balena.exceptions.UnsupportedFeature` on the last line. So I am not sure if I am doing anything wrong.
I also tried to do other operations, such as calling `balena.models.device.get_all()` but I get another error: `balena.exceptions.RequestError: b''`.

Also, is it possible to log in using a Google account via Python SDK? I do use a Google Account on Balena dashboard.

**Comment by otaviojacobi** [comment]
Hello @mfoglio This problem caused by some inconsistency in the logic to check the 2FA `is_passed` on our SDK which should have been fixed in #326 
I just tested with my personal account with 2FA the above code (which had some minor changes in the naming conventions) as:

```python
balena = Balena()
credentials = {
    "username": settings.BALENA_USERNAME,
    "password": settings.BALENA_PASSWORD
}
balena.auth.login(**credentials)
balena.auth.two_factor.challenge("303206")  # OTP code
print(balena.twofactor_auth.is_passed())  # outputs True, which means, user is fully authenticated
```

And it worked fine for me. Please re-test and re-open in case you find any more problems.
