### ISSUE TITLE
cannot set the release version after the recent update

### ISSUE THREAD

**Issue by alireza-moayyedi** [balena-io/balena-sdk-python#328]
Before the last update (v13.0.0) I was able to set the release version simply by:
`Balena.models.release.set_release_version(release_id, my_release_version)`
Looking at the recent changes, I could not find the same functionality. I would be thankful if you could tell me how I can achieve the same functionality now?

**Comment by Timple** [comment]
Directly setting the release with an argument like `balena deploy --release-version 1.2.3` would also be nice. 

The reason we're using the api in the first place is to workaround this missing argument.

**Comment by MCFurry** [comment]
Ahhh I just stumbled across the same issue which now breaks our workflow.

Would be very nice if we can get this working again!

**Comment by otaviojacobi** [comment]
Hello, I am looking into it and will update shortly

**Comment by otaviojacobi** [comment]
Hello @MCFurry @Timple and @alireza-moayyedi This was caused by node api also not having it and I mistakenly erasing it from here. The PR with the fix is open: #329 and once CI passes I will merge and the function will be back up. I will also update node-sdk to contain it for compability reasons. 

Just if it is interesting for you, the balena-python-sdk now allows you to use inner pine query, which means you can achieve this result using the generic pine, so something like:

```python
balena.pine.patch(
   {
     "resource": "release",
     "id": release_id, 
     "body": {
            "semver": my_semver
      }
})
```

Would also have done the trick. Nevertheless the 13.0.1 version with this fix should be released in a few minutes, thanks for opening the issue and do not hesitate if you have more problems with the sdk.

**Comment by Timple** [comment]
Thanks for the fast update!

Where would I need to put the feature request for the commandline option to set it directly? :slightly_smiling_face:

**Comment by otaviojacobi** [comment]
Hello @Timple for feature request I would recommend https://roadmap.balena.io/ or if you want to reach CLI directly an issue here: https://github.com/balena-io/balena-cli 

Once node-sdk has this same feature (I will work on it starting today) we can check if this should be added on the CLI aswell

**Comment by otaviojacobi** [comment]
Hello, #329 was merged and published and the fix should now be live in balena-sdk v13.0.1
I also tested locally with this version and everything looks to be working as expected. Please feel free to reopen in case this issue persists for any of you.

**Comment by MCFurry** [comment]
Thanks for the quick update! Seems to be fine now indeed!

**Comment by alireza-moayyedi** [comment]
@otaviojacobi Thanks a lot for the support!
