### ISSUE TITLE
Error with resin.cfg on application start

### ISSUE THREAD

**Issue by SloMusti** [balena-io/balena-sdk-python#66]
When running an application using this SDK, the error `Settings file not found or not in proper format. Rewriting default settings to: /root/.resin/resin.cfg` is present on every device reboot, where hostOS is rebooted as well. Generally it is harmless, however it appears to take 15s to process this error, which slows down the boot process.

Application in question is the following: https://github.com/IRNAS/PiRA-zero-firmware

We use the Pyhton SDK to issue shutdown and reboot commands to the host os.

**Comment by SloMusti** [comment]
Sample printout of log with delay visible:
```
25.01.18 20:38:37 (+0100) Systemd init system enabled.
25.01.18 20:38:38 (+0100) systemd 215 running in system mode. (+PAM +AUDIT +SELINUX +IMA +SYSVINIT +LIBCRYPTSETUP +GCRYPT +ACL +XZ -SECCOMP -APPARMOR)
25.01.18 20:38:38 (+0100) Detected virtualization 'other'.
25.01.18 20:38:38 (+0100) Detected architecture 'arm'.
25.01.18 20:38:38 (+0100) Set hostname to <a2c4e7a>.
25.01.18 20:38:55 (+0100) Powering off HDMI
25.01.18 20:38:57 (+0100)   Writing RTC time to system...
25.01.18 20:38:58 (+0100)   Done :-)
25.01.18 20:39:13 (+0100) Settings file not found or not in proper format. Rewriting default settings to: /root/.resin/resin.cfg
25.01.18 20:39:14 (+0100) Performing boot sequence.```

**Comment by imrehg** [comment]
I wonder what would be a timeline if in the Dockerfile you'd ship a valid, simple config at `/root/.resin/resin.cfg`. It would be a good test. The hunch is that it's something else that takes 15s to process.

**Comment by SloMusti** [comment]
@imrehg please provide a sample config and I can try

**Comment by nghiant2710** [comment]
Hi @SloMusti, you see that message on every reboot or application restart because the SDK can't find a setting file and it will write a default setting file to your home directory then output that message.

Here is what happens when you use the SDK to trigger reboot and shutdown, first your request will be sent to our API then the API will send reboot/shutdown request to the supervisor on your device, wait for response from supervisor (I'm not so sure about this step) and send the response back to the SDK. This can explain a bit about it takes about 15s to process your request. However, I don't think you should use the SDK to do this since you can interactive with the supervisor directly from application container.

Please check this docs https://docs.resin.io/runtime/supervisor-api/#post-v1-reboot, you can send your reboot/shutdown request directly to the supervisor from your application container, I'm pretty sure that it will take much less time to process.

**Comment by SloMusti** [comment]
Confirming, not using resin SDK resolves this error of not finding the config. 

@imrehg Using the suggested method via curl however may result in the following error which prevents reboot: `curl: (7) Failed to connect to 127.0.0.1 port 48484: Connection refused`
